import turtle
print('Please enter a two digit integer')
first_digit= int(input('Please enter first digit: '))
second_digit= int(input('Please enter second digit: '))
if (first_digit == 0):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
elif (first_digit == 1):
    turtle.left(90)
    turtle.forward(150)
elif (first_digit == 2):
    turtle.left(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (first_digit == 3):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (first_digit == 4):
    turtle.left(90)
    turtle.forward(75)
    turtle.left(180)
    turtle.forward(75/2)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(65)
elif (first_digit == 5):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
elif (first_digit == 6):
    turtle.left(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (first_digit == 7):
    turtle.left(45)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(75)
elif  (first_digit == 8):
    turtle.left(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (first_digit == 9):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
turtle.penup()
turtle.home()
turtle.forward(200)
turtle.pendown()
if (second_digit == 0):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
elif (second_digit == 1):
    turtle.left(90)
    turtle.forward(150)
elif (second_digit == 2):
    turtle.left(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (second_digit == 3):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (second_digit == 4):
    turtle.left(90)
    turtle.forward(75)
    turtle.left(180)
    turtle.forward(75/2)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(65)
elif (second_digit == 5):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
elif (second_digit == 6):
    turtle.left(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (second_digit == 7):
    turtle.left(45)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(75)
elif  (second_digit == 8):
    turtle.left(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
elif (second_digit == 9):
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
